# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec4ccd7c018269000fe338025a48afa243ca3d74c50863b6366d627a180aaa5bf37dd7a6b84f59852f7412bb9e67bd7528e529b85a9127810d8621dc4af7b20c

test:
  secret_key_base: 6f637e2c18098329bc55f14b97487a512a50b1a2f3f204e217be3dec0703da704b2a3bb7eae45adefdef253f3bf86ebcfbd5a8aa61c14c67e658f28d1d0f89f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
