speakers:
  belize-camara:
    talk: Promotor.com
    name: Belize Câmara
    description: Promotora de Justiça do Estado de Pernambuco, apaixonada pela causa ambiental e percursora do uso das redes sociais como instrumento de diálogo com a sociedade.
    photo: belize-camara.jpg
    video: https://www.youtube.com/watch?v=oyBIwgNu4HE
  guilherme-jordao:
    talk: "Cicloativismo: A alforria do caracol"
    name: Guilherme Jordão
    description: Defensor público federal, professor universitário, resolveu adotar a bicicleta como forma de mudar totalmente seu estilo de vida. Hoje é cicloativista e coordenador geral da Ameciclo.
    photo: guilherme-jordao.jpg
    video: http://youtu.be/spc-HHF74vY
  pedro-melo:
    talk: "Troca por um Quadro: A Experiência através da Arte"
    name: Pedro Melo
    description: Designer e Ilustrador, criador do projeto Troca por um Quadro. Pedro trocar sua obra de arte por qualquer coisa que renda uma boa história. Passou 23 dias pela Europa, onde recebeu latas de tinta, hambúrguers, bebias e até hospedagem.
    photo: pedro-melo.jpg
    video: https://www.youtube.com/watch?v=EcnS02V33Oc
  gustavo-maia:
    talk: "Para Mudar uma Nação: Colaboração"
    name: Gustavo Maia
    description: Publicitário e especialista em marketing digital com ênfase em política. Co-fundador do Colab, aplicativo que trabalha a integração entre o cidadão e o poder público, eleito o melhor aplicativo urbano do mundo pelo News Cities Summits.
    photo: gustavo-maia.jpg
    video: http://youtu.be/4Lwu26W9Uk0
  flavia-moura:
    talk: O planeta é meu!
    name: Flávia Moura
    description: Química Industrial, trabalha em indústrias implementando programas de gestão e mudanças de cultura dentro das organizações. Criadora do programa de Coleta Seletiva de Óleo de Fritura, buscando transformar a realidade atual através da educação.
    photo: flavia-moura.jpg
    video: http://youtu.be/ZMFVlAZscLY
  rafa-mattos:
    talk: Plante Amor e Colha o Bem
    name: Rafa Mattos
    description: Artista gráfico que tornou-se conhecido por espalhar pela cidade placas com desenhos e frases “Plante Amor e Colha o Bem”, que são produzidas a partir de uma “garimpagem” alucinante, de quem vê o lixo como matéria-prima.
    photo: rafa-mattos.jpg
    video: http://youtu.be/sNxdIlU4DQE
  andrea-souza:
    talk: Cinoterapia, os Cães Doutores da Alegria
    name: Andrea Souza
    description: Terapeuta ocupacional, implantou a Terapia Assistida por Animais em um Centro de Atenção Psicossocial do Recife, sendo o Espaço LivreMente o primeiro CAPS do Brasil a adotar o recurso terapêutico dos Cães Doutores.
    photo: andrea-souza.jpg
    video: http://youtu.be/3Fssk1iPZqI
  renato-kyiama:
    talk: Geração de Negócios de Impacto
    name: Renato Kyiama
    description: Graduated in Business Administration by the University of São Paulo, with studies in Entrepreneurship at the Babson College (Boston, USA). Acts in the creation and acceleration of social business since 2007. He was mentor and counselor in many startups and participated in the development of the main programs of Artemisia. Conducted field researches about market strategies that could reduce poverty in Brazil, India and Latin America. He is one of the facilitators of processes of innovation, acting as a collaborator in the making of Artemisia and consultant in many organisations (SENAC, Banco Central, FIA e GIFE). At age 16 he started to undertake projects related to the youth and urban culture. He was also director at Artemisia and today he acts as the Institutional Development Director of this organisation.
    photo: renato-kyiama.jpg
    video: http://youtu.be/3qia5j5uT0c
  leonardo-cisneiros:
    talk: Direitos urbanos, a cidade é nossa!
    name: Leonardo Cisneiros
    description: Leonardo is a Filosophy professor at the Rural Federal University of Pernambuco and one of the 14 thousand members of Urban Rights Recife, a group that started on the social networks as a place to bring together people interested in discussing the targets of Recife and was able to "get off the sofa" to occupy the streets and fight for a more human and fair city.
    photo: leonardo-cisneiros.jpg
    video: http://youtu.be/QZtIT3-BN2w
